name: pmplast_kiosk
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3
  flutter_riverpod: ^2.0.0
  mobile_scanner: ^3.0.0
  camera: ^0.11.2+1
  geolocator: ^14.0.2
  image: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.0
  connectivity_plus: ^5.0.0
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^12.2.0
  permission_handler: ^12.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
